version: 1
builds:
  - main: ./cmd/go2junit
    binary: go2junit
    ldflags:
      - -s -w -X "github.com/fasmat/go2junit/cmd/go2junit/main.version={{ .Version }}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - "386"
      - arm64

archives:
  - name_template: "go2junit_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
release:
  header: |
    ## {{ .Date }} go2junit {{ .Tag }}
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
